echo "**************************************************************************************************"
echo "Author      : Prajyot Gupta"
echo "Contact     : pgupta54@wisc.edu"
echo "Research    : Dynamic Predication of H2P Branches"
echo "Description : This script runs ChampSim to generate Branch Prediction data for Spec17 benchmarks"
echo "Benchmark   : $1"
echo "**************************************************************************************************"
echo ""
echo "Started running Perceptron based BP"
echo ""
./run_champsim.sh perceptron-no-no-no-no-lru-1core 1 25 $1 
echo ""
echo "Finished running Perceptron based BP"
echo ""
echo "*************************************************************************************************"
echo ""
echo "Started running Simulation with No Branch Prediction"
echo ""
./run_champsim.sh bimodal_No_BP  1 25 $1 
echo ""
echo "Finished running Simulation with No Branch Prediction"
echo ""
echo "*************************************************************************************************"
echo ""
echo "Started running Simulation with the ORACLE Branch Predictor"
echo ""
./run_champsim.sh bimodel_ORACLE 1 25 $1 
echo ""
echo "Finished running Simulation with the ORACLE Branch Predictor"
echo ""
echo "*************************************************************************************************"
echo ""
echo " Regression Completed! "
echo ""
echo "*************************************************************************************************"
